# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      build:
        patterns:
          - copy-webpack-plugin
          - css-loader
          - mini-css-extract-plugin
          - npm-run-all
          - resolve-url-loader
          - rimraf
          - sass
          - sass-loader
          - "webpack-*"
          - webpack
      test:
        patterns:
          - backstopjs
          - fast-glob
          - http-server
          - serve-static
      lint:
        patterns:
          - husky
          - lint-staged
          - prettier
          - "stylelint-*"
          - stylelint
