# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

registries:
  npm-github:
    type: npm-registry
    url: "https://npm.pkg.github.com"
    token: ${{ secrets.REPO_READ_ONLY_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - npm-github
    groups:
      build:
        - copy-webpack-plugin
        - css-loader
        - mini-css-extract-plugin
        - npm-run-all
        - resolve-url-loader
        - rimraf
        - sass
        - sass-loader
        - "webpack-*"
        - webpack
      test:
        - backstopjs
        - fast-glob
        - http-server
        - serve-static
      lint:
        - husky
        - lint-staged
        - prettier
        - "stylelint-*"
        - stylelint
