version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "iRealisatie - Ministerie van Volksgezondheid, Welzijn en Sport"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = ["fonts/**", "img/**"]
SPDX-FileCopyrightText = "Ministry of General Affairs of the Netherlands"
SPDX-License-Identifier = "LicenseRef-Rijkshuisstijl"
