name: CI

on:
  pull_request:

  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dependencies
        uses: ./.github/actions/setup
        with:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
      - name: Run linter
        run: npm run lint
        continue-on-error: true

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dependencies
        uses: ./.github/actions/setup
        with:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
      - name: Check formatting
        run: npm run format:check

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dependencies
        uses: ./.github/actions/setup
        with:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
      - name: Build docs
        run: npm run build

  visual-test:
    name: Visual regression test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dependencies
        uses: ./.github/actions/setup
        with:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
      - name: Install firefox
        uses: browser-actions/setup-firefox@v1
      - run: firefox --version
      - name: Run visual regression test
        run: npm run visual:ci
      - name: Generate job summary
        uses: test-summary/action@v2
        with:
          paths: visual-test/ci_report/xunit.xml
        if: always()
