name: CI

on:
  pull_request:

  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Audit dependencies
        uses: ./.github/actions/setup
        with:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
          audit-level: moderate

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dependencies
        uses: ./.github/actions/setup
        with:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
      - name: Run linter
        run: npm run lint
        continue-on-error: true
      - name: Check formatting
        run: npm run format:check

  visual-test:
    name: Visual regression test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dependencies
        uses: ./.github/actions/setup
        with:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
      - name: Setup firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest-esr
      - run: firefox --version
      - name: Build docs
        run: npm run build
      - name: Run visual regression test
        run: npm run visual:ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_PRODUCT: firefox
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-firefox.outputs.firefox-path }}
      - name: Generate job summary
        uses: test-summary/action@v2
        with:
          paths: visual-test/ci_report/xunit.xml
        if: ${{ always() && hashFiles('visual-test/ci_report/xunit.xml') }}
      - name: Upload visual test report
        uses: actions/upload-artifact@v4
        with:
          name: visual-test-report
          path: |
            visual-test/html_report/
            visual-test/bitmaps_*/
        if: ${{ always() && hashFiles('visual-test/html_report/index.html') }}
